=begin
#PacerPro

#PacerPro API documentation.

OpenAPI spec version: 0.4.0
Contact: ken@pacerpro.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for PacerProClient::CasesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CasesApi' do
  before do
    # run before each test
    @instance = PacerProClient::CasesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CasesApi' do
    it 'should create an instact of CasesApi' do
      expect(@instance).to be_instance_of(PacerProClient::CasesApi)
    end
  end

  # unit tests for cases_get_collection
  # A collection of cases.
  # Get all cases related to your account.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization Bearer {...JSON Web Token...}
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Limit number of objects returned per page
  # @return [Array<ModelCase>]
  describe 'cases_get_collection test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cases_get_one
  # A single case.
  # Get a single case, specified by &#x60;caseId&#x60; in the path.
  # @param case_id The database identifier of the case.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization Bearer {...JSON Web Token...}
  # @return [ModelCase]
  describe 'cases_get_one test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cases_get_parties
  # A table of parties.
  # A parsed, structured table of the listed parties in the case.
  # @param case_id The database identifier of the case.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization Bearer {...JSON Web Token...}
  # @return [Array<Party>]
  describe 'cases_get_parties test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
