=begin
#PacerPro

#PacerPro API documentation.

OpenAPI spec version: 0.2.1
Contact: ken@pacerpro.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for PacerProClient::MattersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MattersApi' do
  let(:api_client) { authenticate_for_testing }

  before do
    # run before each test
    @instance = PacerProClient::MattersApi.new(api_client)
  end

  after do
    # run after each test
  end

  describe 'test an instance of MattersApi' do
    it 'should create an instact of MattersApi' do
      expect(@instance).to be_instance_of(PacerProClient::MattersApi)
    end
  end

  # unit tests for matters_get
  # A collection of matters.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization &#x60;Bearer {...JSON Web Token...}&#x60;
  # @return [Matters]
  describe 'matters_get test' do
    it "should work" do
      expect(@instance.matters_get).to match(PacerProClient::Matters.new)
    end
  end

  # unit tests for matters_matter_id_get
  # A single matter.
  # 
  # @param matter_id The database identifier of the matter.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization &#x60;Bearer {...JSON Web Token...}&#x60;
  # @return [Matter]
  describe 'matters_matter_id_get test' do
    it "should work" do
      matters = @instance.matters_get()
      expect(matter = matters.first).to be_instance_of(PacerProClient::Matter)
      expect(@instance.matters_matter_id_get(matter.id)).to be_instance_of(PacerProClient::Matter)
    end

    it "should raise an error if not found" do
      expect { @instance.matters_matter_id_get('abc') }
        .to raise_error(PacerProClient::ApiError, 'Not Found')
    end
  end

end
