=begin
#PacerPro

#PacerPro API documentation.

OpenAPI spec version: 0.2.1
Contact: ken@pacerpro.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PacerProClient::Matter
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Matter' do
  before do
    # run before each test
    @instance = PacerProClient::Matter.new
    @instance.build_from_hash({
                                id:                 'matterId',
                                caseId:             'caseId',
                                clientMatterNumber: 'clientMatterNumber',
                                judge:              'ABC',
                                caseNumber:         '1:17-cv-123456-ABC',
                                caseTitle:          'caseTitle',
                                natureOfSuit:       'natureOfSuit',
                                docketEntries:      123,
                                activityAt:         '2017-07-13T20:49:31.706Z',
                              })
  end

  after do
    # run after each test
  end

  describe 'test an instance of Matter' do
    it 'should create an instact of Matter' do
      expect(@instance).to be_instance_of(PacerProClient::Matter)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      expect(@instance.id).to eq('matterId')
    end
  end

  describe 'test attribute "case_id"' do
    it 'should work' do
      expect(@instance.case_id).to eq('caseId')
    end
  end

  describe 'test attribute "client_matter_number"' do
    it 'should work' do
      expect(@instance.client_matter_number).to eq('clientMatterNumber')
    end
  end

  describe 'test attribute "judge"' do
    it 'should work' do
      expect(@instance.judge).to eq('ABC')
    end
  end

  describe 'test attribute "case_number"' do
    it 'should work' do
      expect(@instance.case_number).to eq('1:17-cv-123456-ABC')
    end
  end

  describe 'test attribute "case_title"' do
    it 'should work' do
      expect(@instance.case_title).to eq('caseTitle')
    end
  end

  describe 'test attribute "nature_of_suit"' do
    it 'should work' do
      expect(@instance.nature_of_suit).to eq('natureOfSuit')
    end
  end

  describe 'test attribute "docket_entries"' do
    it 'should work' do
      expect(@instance.docket_entries).to eq(123)
    end
  end

  describe 'test attribute "activity_at"' do
    it 'should work' do
      expect(@instance.activity_at).to eq(DateTime.new(2017, 7, 13, 20, 49, 31.706, "+00:00"))
    end
  end

end

